# Generated by Django 6.0.8 on 2026-09-18 21:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-month']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_off_floor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 18, 21, 9, 20, 164160, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payslip',
            name='penalty_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='base_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('user', 'month')},
        ),
        migrations.CreateModel(
            name='SuddenAbsenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('absence_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open — Not Returned'), ('returned', 'Returned'), ('approved', 'Approved Leave'), ('penalised', 'Penalised')], default='open', max_length=12)),
                ('admin_note', models.TextField(blank=True)),
                ('notified_admin', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to='payroll.staffshift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
