# Generated by Django 6.0.8 on 2026-09-18 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zk_pin', models.CharField(db_index=True, help_text='Unique ZKTeco hardware PIN', max_length=20, unique=True)),
                ('card_number', models.CharField(blank=True, help_text='RFID / Proximity card number', max_length=50, null=True)),
                ('face_enrolled', models.BooleanField(default=False, help_text='Face template enrolled on terminal')),
                ('fingerprint_enrolled', models.BooleanField(default=False, help_text='Fingerprint template enrolled')),
                ('door_group_id', models.IntegerField(default=1, help_text='ZKBio access level / door group ID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCED', 'Synced with Hardware'), ('FAILED', 'Hardware Sync Failed'), ('REVOKED', 'Revoked / Disabled')], db_index=True, default='PENDING', max_length=20)),
                ('disabled', models.BooleanField(default=False, help_text='Hardware door permission revoked if subscription expires or user suspended')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Profile',
                'verbose_name_plural': 'Biometric Profiles',
                'ordering': ['zk_pin'],
            },
        ),
        migrations.CreateModel(
            name='DoorAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zk_pin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('punch_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry Granted'), ('EXIT', 'Exit Granted'), ('DENIED', 'Access Denied'), ('ANTI_PASSBACK', 'Anti-Passback Blocked')], db_index=True, max_length=20)),
                ('device_ip', models.GenericIPAddressField(default='192.168.1.23')),
                ('terminal_name', models.CharField(default='MAIN_TURNSTILE', max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Door Access Log',
                'verbose_name_plural': 'Door Access Logs',
                'ordering': ['-punch_time'],
            },
        ),
    ]
