# Generated by Django 6.0.8 on 2026-09-18 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkbio_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dooraccesslog',
            name='verify_mode',
            field=models.CharField(choices=[('FACE_ID', 'Face Recognition'), ('FINGERPRINT', 'Fingerprint'), ('BUZZER', 'Manual Override'), ('CARD', 'RFID Card')], default='FACE_ID', max_length=20),
        ),
        migrations.CreateModel(
            name='BiometricCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('ENROLL_FP', 'Enroll Fingerprint on Turnstile Terminal'), ('UPLOAD_FACE', 'Upload Face Template / Photo to Terminal'), ('REMOTE_BUZZ', 'Pulse Turnstile Relay Open (5s)'), ('REVOKE_USER', 'Revoke Access & Delete from Terminal')], max_length=30)),
                ('zk_pin', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Execution'), ('IN_PROGRESS', 'Executing on Device'), ('COMPLETED', 'Successfully Completed'), ('FAILED', 'Execution Failed')], db_index=True, default='PENDING', max_length=20)),
                ('device_ip', models.GenericIPAddressField(default='192.168.1.23')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Command',
                'verbose_name_plural': 'Biometric Commands',
                'ordering': ['-created_at'],
            },
        ),
    ]
