# Generated by Django 6.0.8 on 2026-09-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkbio_integration', '0002_dooraccesslog_verify_mode_biometriccommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricprofile',
            name='liveu_id',
            field=models.CharField(blank=True, db_index=True, help_text='LiveU Cloud MongoDB _id for cloud-managed hardware sync', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dooraccesslog',
            name='liveu_attendance_id',
            field=models.CharField(blank=True, db_index=True, help_text='LiveU attendance record _id', max_length=64, null=True, unique=True),
        ),
    ]
