# Generated by Django 6.0.8 on 2026-09-18 22:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='health_notes',
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='agreed_to_rules',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='fitness_goals_other',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=15),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='has_medical_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='is_under_medication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='medical_condition_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='medication_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='nic_passport',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIC / Passport No'),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='personal_trainer_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='plan_duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nic_passport',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIC / Passport No'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='personal_trainer_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='under_medication',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='desired_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershipplan'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='primary_goal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
