# Generated by Django 6.0.8 on 2026-09-18 22:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_remove_memberapplication_health_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('info', 'Information'), ('warning', 'Operational Notice'), ('critical', 'Urgent / Important')], default='info', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('subject', models.CharField(default='Membership / Training Inquiry', max_length=150)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('hypertrophy', 'Hypertrophy & Muscle Build'), ('fat_loss', 'Fat Loss & Shred'), ('strength', 'Power & Strength'), ('hiit', 'HIIT & Conditioning'), ('calisthenics', 'Bodyweight & Calisthenics'), ('personal_training', '1-on-1 Personal Training')], default='hypertrophy', max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced / Athlete')], default='intermediate', max_length=20)),
                ('duration_weeks', models.IntegerField(default=8)),
                ('sessions_per_week', models.IntegerField(default=4)),
                ('description', models.TextField()),
                ('key_features', models.TextField(help_text='Comma-separated or newline list of features')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('program_name', models.CharField(default='Fit Me 12-Week Transformation', max_length=100)),
                ('quote', models.TextField()),
                ('weight_loss_kg', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('muscle_gain_kg', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('duration_months', models.IntegerField(default=3)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/before/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/after/')),
                ('is_featured', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certified Strength & Conditioning Coach', max_length=100)),
                ('specialties', models.CharField(help_text='e.g. Hypertrophy, Sri Lankan Nutrition, Powerlifting', max_length=200)),
                ('certifications', models.CharField(blank=True, max_length=250)),
                ('years_experience', models.IntegerField(default=5)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='coaches/avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('biceps_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('thighs_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitme_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MemberWorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(default='Push Day', max_length=100)),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets_completed', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitme_workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
