# Generated by Django 6.0.8 on 2026-09-30 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_announcement_contactinquiry_gymprogram_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='assigned_program',
            field=models.ForeignKey(blank=True, help_text='Currently active gym training program assigned by coach', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='membership.gymprogram'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='allowed_entry_end',
            field=models.TimeField(blank=True, help_text='Latest allowed entry time (leave blank for unrestricted)', null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='allowed_entry_start',
            field=models.TimeField(blank=True, help_text='Earliest allowed entry time (leave blank for unrestricted)', null=True),
        ),
    ]
