# Generated by Django 6.0.8 on 2026-09-18 20:34

import wger.gallery.models.image
import wger.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', help_text='Only PNG and JPEG formats are supported', upload_to=wger.gallery.models.image.gallery_upload_dir, validators=[wger.utils.images.validate_image_static_no_animation], verbose_name='Image', width_field='width'),
        ),
    ]
