# Generated by Django 6.0.8 on 2026-09-18 21:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('plan_type', models.CharField(choices=[('SINGLE', 'Single Member'), ('COUPLES', 'Couples / Buddy (2 Users, 1 Billing Entity)'), ('STUDENT', 'Student'), ('OFF_PEAK', 'Off-Peak Window Restricted')], default='SINGLE', max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('max_members', models.IntegerField(default=1, help_text='Set to 2 for Couples/Buddy plan')),
                ('allowed_entry_start', models.TimeField(default='00:00:00', help_text='Allowed entry window start')),
                ('allowed_entry_end', models.TimeField(default='23:59:59', help_text='Allowed entry window end')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_member', models.ForeignKey(blank=True, help_text='Primary billing entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_billed_plans', to=settings.AUTH_USER_MODEL)),
                ('secondary_member', models.ForeignKey(blank=True, help_text='Buddy member linked to primary billing entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(db_index=True)),
                ('scheduled_start', models.TimeField()),
                ('scheduled_end', models.TimeField()),
                ('actual_first_in', models.DateTimeField(blank=True, null=True)),
                ('actual_last_out', models.DateTimeField(blank=True, null=True)),
                ('unapproved_absence_minutes', models.IntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('is_off_floor', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ON_FLOOR', 'On Floor (Active)'), ('OFF_FLOOR', 'Off Floor — Unapproved Departure'), ('LEAVE', 'Approved Leave'), ('COMPLETED', 'Shift Completed')], default='SCHEDULED', max_length=20)),
                ('approved_leave', models.BooleanField(default=False)),
                ('leave_reason', models.TextField(blank=True)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8)),
                ('staff_user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Shift',
                'verbose_name_plural': 'Staff Shifts',
                'ordering': ['-shift_date', 'scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SuddenAbsenceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('minutes_off_floor', models.IntegerField(default=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to='gym_operations_payroll.staffshift')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_absence_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sudden Absence Alert',
                'verbose_name_plural': 'Sudden Absence Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of payroll month, e.g. 2026-09-01')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pt_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Personal Training session commissions', max_digits=10)),
                ('late_minutes_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sudden_absence_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Ledger',
                'verbose_name_plural': 'Payroll Ledgers',
                'ordering': ['-month', 'staff_user'],
                'unique_together': {('staff_user', 'month')},
            },
        ),
    ]
