# Generated by Django 6.0.8 on 2026-09-18 22:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_operations_payroll', '0001_initial'),
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(default=30)),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(default='cash', max_length=30)),
                ('member_pin', models.CharField(blank=True, help_text='Assigned hardware turnstile PIN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='membership.subscription')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BuddyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_buddy_memberships', to=settings.AUTH_USER_MODEL)),
                ('primary_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_buddy_memberships', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_links', to='membership.subscription')),
            ],
            options={
                'verbose_name': 'Buddy Membership',
                'verbose_name_plural': 'Buddy Memberships',
                'unique_together': {('primary_member', 'partner_member')},
            },
        ),
    ]
