# Generated by Django 6.0.8 on 2026-09-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_operations_payroll', '0002_paymentreceipt_buddymembership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
