# Generated by Django 6.0.8 on 2026-09-18 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_synced', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=10, unique=True)),
                ('last_sync_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zkbio_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoorPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField()),
                ('terminal_id', models.CharField(default='MAIN_GATE', max_length=50)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_punches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
