# Generated by Django 6.0.8 on 2026-09-18 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='English name', max_length=120)),
                ('name_si', models.CharField(blank=True, help_text='Sinhala name (transliterated)', max_length=120)),
                ('category', models.CharField(choices=[('rice_grains', 'Rice & Grains'), ('curry_stew', 'Curries & Stews'), ('protein', 'Protein / Meat / Fish / Eggs'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy & Alternatives'), ('snacks', 'Snacks & Street Food'), ('beverages', 'Beverages'), ('supplements', 'Supplements & Powders')], default='rice_grains', max_length=30)),
                ('calories_per_100g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_serving_g', models.IntegerField(default=100)),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='DailyFuelTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories', models.IntegerField(default=2000)),
                ('target_protein_g', models.IntegerField(default=150)),
                ('target_carbs_g', models.IntegerField(default=200)),
                ('target_fat_g', models.IntegerField(default=65)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_target', to=settings.AUTH_USER_MODEL)),
                ('set_by_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.IntegerField(default=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition_lk.localfood')),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], default='lunch', max_length=20)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meals/photos/')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('coach_reviewed', models.BooleanField(default=False)),
                ('coach_feedback', models.TextField(blank=True)),
                ('total_calories', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
                ('entries', models.ManyToManyField(blank=True, to='nutrition_lk.meallogentry')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
