# Generated by Django 6.0.8 on 2026-09-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_type', models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Note'), ('nudge', 'Auto Nudge (Missed Workout)'), ('feedback', 'Meal Feedback'), ('achievement', 'Achievement Badge')], default='text', max_length=15)),
                ('message', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='habit/voice_notes/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pings', to=settings.AUTH_USER_MODEL)),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('total_checkins', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
